api/urls.py
from rest_framework import routers

from api.views import SecretKeyViewSet

router = routers.DefaultRouter()

router.register('secrets', SecretKeyViewSet, 'secrets')

urlpatterns = router.urls

bookmark/urls.py
from django.urls import path

from . import views
from bookmark import feeds

app_name = 'bookmark'
urlpatterns = [
    path('', views.BookmarkListView.as_view(), name='bookmark-list'),
    path('search/', views.SearchView.as_view(), name='search'),
    path('tags/<slug:tag_slug>/',
         views.BookmarkListByTagListView.as_view(),
         name='bookmark-list-by-tag'),
    path('tags/<slug:tag_slug>/feed/', feeds.BookmarksByTagFeed(),
         name='bookmark-list-by-tag-feed'),
    path('<slug:bookmark_slug>/', views.BookmarkDetailView.as_view(),
         name='bookmark-detail'),
]

changelog/urls.py
from django.urls import path

from . import views

app_name = 'changelog'
urlpatterns = [
    path('', views.ChangelogListView.as_view(),
         name='changelog-list'),
    path('<slug:changelog_slug>/',
         views.ChangelogDetailView.as_view(), name='changelog-detail'),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.views.generic.base import RedirectView, TemplateView

from . import views, feeds

app_name = 'core'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),

    # REDIRECTS

    path('favicon.ico',
         RedirectView.as_view(url='static/img/favicon.ico', permanent=True),
         name='favicon'),
    path('index.xml', RedirectView.as_view(url='/feed/'), name='go-to-feed'),

    # OTHER SECTIONS WITH CUSTOM URLS

    path('humans.txt',
         TemplateView.as_view(template_name="core/humans.txt",
                              content_type='text/plain'),
         name='humans'),
    path('articles/', views.ArticleListView.as_view(), name='article-list'),
    path('feed/', feeds.LatestEntriesFeed(), name='feed'),
    path('feed/json/', views.JsonFeedView.as_view(), name='json-feed'),
    path('search/', views.SearchView.as_view(), name='search'),

    # TAGS

    path('tags/', views.TagListView.as_view(), name='tag-list'),
    # posts (articles, pages, and notes) by tag
    path('tags/<slug:tag_slug>/', views.PostsByTagListView.as_view(),
         name='post-list-by-tag'),
    # posts by tag feed
    path('tags/<slug:tag_slug>/feed/', feeds.EntriesByTagFeed(),
         name='post-list-by-tag-feed'),

    # PAGES AND ARTICLES

    # page detail or articles by category
    path('<slug:page_slug>/', views.PageOrCategoryView.as_view(),
         name='page-detail-or-article-list-by-category'),
    # articles by category feed
    path('<slug:category_slug>/feed/', feeds.EntriesByCategoryFeed(),
         name='article-list-by-category-feed'),
    # article detail
    path('<slug:category_slug>/<slug:article_slug>/',
         views.ArticleDetailView.as_view(), name='article-detail')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

note/urls.py
from django.urls import path

from . import views

app_name = 'note'
urlpatterns = [
    path('', views.NoteListView.as_view(), name='note-list'),
    path('<slug:note_slug>/', views.NoteDetailView.as_view(),
         name='note-detail'),
]

bookmark/models.py
from django.db import models
from django.urls import reverse

from core.models import Post
from core.utils.post import PostType


class Bookmark(Post):
    site_url = models.URLField(unique=True)
    content = models.TextField(blank=True)
    content_html = models.TextField(blank=True, editable=False)
    pub_type = models.CharField(choices=PostType.POST_TYPES,
                                default=PostType.BOOKMARK, max_length=10)

    def get_absolute_url(self):
        return reverse('bookmark:bookmark-detail',
                       kwargs={'bookmark_slug': self.slug})

    def __str__(self):
        return self.title

bookmark/views.py
from django.db.models import Q, Count
from django.shortcuts import redirect, render
from django.utils import timezone
from django.views import View
from django.views.generic import ListView, DetailView

from bookmark.models import Bookmark
from core.entry import Entry
from core.models import Tag
from core.utils.post import PostStatus, RECENTLY

RECENTLY **= 2


def get_popular_tags():
    """Get the RECENTLY popular tags"""
    # Popular list: https://stackoverflow.com/a/11127523
    return Tag.objects.annotate(bookmark_count=Count("bookmark")).order_by(
        "-bookmark_count"
    )[:RECENTLY]


def get_number_of_bookmarks_in_the_current_month():
    now = timezone.now()
    return Bookmark.objects.filter(
        Q(pub_date__year=now.year) & Q(pub_date__month=now.month)
    ).count()


class BookmarkListView(ListView):
    """Bookmark list"""

    paginate_by = RECENTLY

    def get_queryset(self):
        return Entry.get_published_bookmark_list()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["popular_tags"] = get_popular_tags()
        current_month_amount = get_number_of_bookmarks_in_the_current_month()
        context["current_month_total_bookmarks"] = current_month_amount
        return context


class BookmarkDetailView(DetailView):
    """Bookmark detail"""

    model = Bookmark
    slug_url_kwarg = "bookmark_slug"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["popular_tags"] = get_popular_tags()
        current_month_amount = get_number_of_bookmarks_in_the_current_month()
        context["current_month_total_bookmarks"] = current_month_amount
        return context


class BookmarkListByTagListView(ListView):
    """
    Bookmark list by tag
    """

    paginate_by = RECENTLY

    def get(self, *args, **kwargs):
        if not self.kwargs["tag_slug"].islower():
            return redirect(
                "bookmark:bookmark-list-by-tag", self.kwargs["tag_slug"].lower()
            )
        return super().get(*args, **kwargs)

    def get_queryset(self):
        return Entry.get_published_bookmark_list().filter(
            tags__slug=self.kwargs["tag_slug"]
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["popular_tags"] = get_popular_tags()
        context["tag"] = Tag.objects.get(slug=self.kwargs["tag_slug"])
        current_month_amount = get_number_of_bookmarks_in_the_current_month()
        context["current_month_total_bookmarks"] = current_month_amount
        return context


class SearchView(View):
    def get(self, request, *args, **kwargs):
        q = request.GET.get("q") or None

        if q is None:
            return redirect("bookmark:bookmark-list")

        bookmark_search_result_list = (
            Bookmark.objects.select_related("author")
            .prefetch_related("tags")
            .filter(
                Q(status=PostStatus.PUBLISHED),
                Q(pub_date__date__lte=timezone.now()),
                Q(title__icontains=q)
                | Q(content__icontains=q)
                | Q(tags__name__icontains=q),
            )
            .order_by("-pub_date")
            .distinct()
        )

        search_result_list = bookmark_search_result_list
        popular_tags = get_popular_tags()
        current_month_amount = get_number_of_bookmarks_in_the_current_month()
        current_month_total_bookmarks = current_month_amount

        return render(
            request,
            "bookmark/search_result.html",
            {
                "search_result_list": search_result_list,
                "search_term": q,
                "current_month_total_bookmarks": current_month_total_bookmarks,
                "popular_tags": popular_tags,
            },
        )

bookmark/templates/bookmark/base.html
<!DOCTYPE html>{% load static %}
<html lang="es">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>{% block titlepage %}Gustavo Huarcaya{% endblock %}</title>
  <link rel="preload" href="{% static 'css/tailwind.min.css' %}" as="style" onload="this.onload=null;this.rel='stylesheet'">
  <noscript><link rel="stylesheet" href="{% static 'css/tailwind.min.css' %}"></noscript>
  <link rel="preload" href="{% static 'css/fontawesome.min.css' %}" as="style" onload="this.onload=null;this.rel='stylesheet'">
  <noscript><link rel="stylesheet" href="{% static 'css/fontawesome.min.css' %}"></noscript>
  <link rel="preload" href="{% static 'css/app.css' %}" as="style" onload="this.onload=null;this.rel='stylesheet'">
  <noscript><link rel="stylesheet" href="{% static 'css/app.css' %}"></noscript>
  {% block feed %}
  <link rel="alternate" href="{% url 'core:feed' %}" type="application/atom+xml" title="Gustavo Huarcaya (Atom)">
  <link rel="alternate" href="{% url 'core:json-feed' %}" type="application/feed+json" title="Gustavo Huarcaya (JSON)" />{% endblock %}
  <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon">
  <link rel="canonical" href="{{ request.scheme }}://{{ request.get_host }}{{ request.get_full_path }}">
  <link type="text/plain" rel="author" href="{% url 'core:humans' %}">
  {% block meta %}
  <meta name="description" content="Gustavo Huarcaya's Personal Page">
  <meta name="keywords" content="gustavo huarcaya, gustavo, huarcaya">{% endblock %}
  {% block ogp %}
  <meta property="og:title" content="Gustavo Huarcaya">
  <meta property="og:description" content="Gustavo Huarcaya's Personal Page">
  <meta property="og:type" content="website">
  <meta property="og:url" content="{{ request.scheme }}://{{ request.get_host }}{{ request.get_full_path }}">
  <meta property="og:site_name" content="gahd.net">
  <meta property="og:image" content="{{ request.scheme }}://{{ request.get_host }}{% static 'img/inti.png' %}">
  {% endblock %}
  <script async src="https://analytics.umami.is/script.js" data-website-id="ecee205e-815b-43cc-a5ad-4dc41f8d56d9"></script>
</head>
<body>
  {% block header %}
  <header class="container mx-auto my-3 px-8 lg:px-32">
    <nav class="flex flex-col sm:flex-row space-y-2 sm:space-y-0 justify-between">
      <a class="flex flex-row space-x-3 items-center" href="{% url 'bookmark:bookmark-list' %}">
        <img class="rounded-none" src="{% static 'img/delicious.gif' %}" alt="logo">
        <div class="flex flex-col">
          <div class="text-2xl font-semibold">delicioso</div>
          <div class="text-gray-400 font-medium sm:font-semibold">anti-social bookmarking</div>
        </div>
      </a>
      <ul class="flex flex-row text-xs font-semibold space-x-0.5">
        <li class="flex items-end w-20 pb-1">It's Free!</li>
        <li class="flex items-end bg-lime-500 text-white indent-3 w-32 pb-1">Join Now</li>
        <li class="flex items-end bg-blue-500 text-white indent-3 w-32 pb-1">Sign In</li>
      </ul>
    </nav>
  </header>
  {% endblock header %}
  {% block hero %}
  <section class="container mx-auto px-8 lg:px-32">
    <a href="{% url 'bookmark:bookmark-list' %}">
      <div class="bg-blue-500 text-white my-4 py-4 px-6">
        <div class="text-2xl font-medium">The tastiest bookmarks on the web.</div>
        <div class="sm:h-16">These are the tastiest bookmarks being saved on Delicioso right now by me.</div>
        <div class="text-sm"><i class="fa-solid fa-circle-question"></i> Learn More</div>
      </div>
    </a>
  </section>
  <section class="container mx-auto px-8 lg:px-32">
    <div class=" bg-gray-200 my-4 px-2 py-1 flex flex-row justify-end xl:justify-between items-center">
      <div class="hidden xl:flex xl:flex-row text-gray-600">
        <span><b>Search</b> the biggest collection of bookmarks in the universe...</span>
      </div>
      <form action="{% url 'bookmark:search' %}" method="GET">
        <input type="text" name="q" placeholder="Search Delicioso" class="outline-none px-2 py-1 text-sm">
        <button type="submit" class="bg-[#7CBA0F] text-white outline-none px-2 py-1 text-sm">Search</button>
      </form>
    </div>
  </section>
  {% endblock hero %}
  {% block content %}{% endblock content %}
  {% block footer %}
  <footer class="container mx-auto px-8 lg:px-32">
    <div class="bg-blue-500 my-4 flex flex-col sm:flex-row justify-between text-xs">
      <div class="bg-blue-500 text-white p-1">
        <ul class="flex flex-col sm:flex-row justify-around space-y-1 sm:space-y-0 sm:space-x-4 sm:divide-x indent-3">
          <li class="hover:underline"><a href="{% url 'core:index' %}" title="Home">home</a></li>
          <li class="hover:underline"><a href="{% url 'core:article-list' %}" title="Articles">articles</a></li>
          <li class="hover:underline"><a href="{% url 'note:note-list' %}" title="Notes">notes</a></li>
          <li class="hover:underline"><a href="{% url 'bookmark:bookmark-list' %}" title="Bookmarks">bookmarks</a></li>
        </ul>
      </div>
      <div class="bg-lime-500 text-white px-1 sm:px-2 py-1 sm:border-l-2 sm:border-l-white hover:underline indent-3 sm:indent-0">
        <a href="{% url 'changelog:changelog-list' %}" title="Changelog">What's new?</a>
      </div>
    </div>
  </footer>
  {% endblock footer %}
  <script defer src="{% static 'js/alpine.min.js' %}"></script>
</body>
</html>

bookmark/templates/bookmark/bookmark_detail.html
{% extends "bookmark/base.html" %}{% load static %}
{% block titlepage %}{% if bookmark %}{{ bookmark.title }} - {{ block.super }}{% else %}{{ block.super }}{% endif %}{% endblock %}
{% block content %}

<section class="container mx-auto px-8 lg:px-32 my-4 flex flex-col">
  {% include "bookmark/content_tabs.html" %}
  <div class="border-y-4 border-t-blue-500 border-b-gray-300 pt-3 pb-2 mb-3">
    <div class="text-gray-700">
      The most latest bookmarks on Delicioso right now
    </div>
    <div class="flex flex-col sm:flex-row space-y-2 sm:space-y-0 justify-between text-xs">
      <p class="text-blue-600 font-semibold">
        <a href="{% url 'bookmark:bookmark-list' %}"><i class="fa-solid fa-bookmark"></i> See more latest bookmarks</a>
      </p>
      <p>
        <span class="text-gray-400">New bookmarks saved in the month</span>
        <span class="bg-blue-500 text-white p-1">{{ current_month_total_bookmarks }}</span>
      </p>
    </div>
  </div>
  <div class="flex flex-row space-x-6">
    <div class="sm:basis-5/6">
      {% if bookmark %}
        {% if bookmark.is_public %}
        <div class="flex flex-col border-b border-b-gray-200 mb-2 pb-1">
          <div class="">
            <a href="{{ bookmark.site_url }}" rel="nofollow" class="text-blue-600 hover:underline">{{ bookmark.title }}</a>
          </div>
          {% if bookmark.tags.count %}
          <div class="flex flex-col sm:flex-row justify-between sm:space-x-0.5 space-y-0.5 sm:space-y-0">
            <span class="flex flex-row">
              <span class="text-[11px] bg-gray-50 text-gray-300 px-1"><i class="fa-regular fa-calendar"></i> {{ bookmark.pub_date|date:"DATE_FORMAT" }}</span>
            </span>
            <span class="flex flex-colum space-x-0.5">
              {% for tag in bookmark.tags.all %}
              <span class="text-[11px] bg-gray-200 text-gray-500 px-1 hover:bg-gray-500 hover:text-white">
                <a href="{% url 'bookmark:bookmark-list-by-tag' tag.slug %}">{{ tag.name }}</a>
              </span>
              {% endfor %}
            </span>
          </div>
          {% endif %}
        </div>
        {% elif not bookmark.is_public and user == bookmark.author %}
        <div class="flex flex-col border-b border-b-gray-200 bg-blue-50 mb-2 pb-1">
          <div class="flex justify-between items-start">
            <a href="{{ bookmark.site_url }}" rel="nofollow" class="text-blue-600 hover:underline">
              {{ bookmark.title }}
            </a>
            <span class="bg-blue-500 text-white text-[11px] px-1">private</span>
          </div>
          {% if bookmark.tags.count %}
          <div class="flex flex-col sm:flex-row justify-between sm:space-x-0.5 space-y-0.5 sm:space-y-0">
            <span class="flex flex-row">
              <span class="text-[11px] bg-blue-100 text-blue-400 px-1"><i class="fa-regular fa-calendar"></i> {{ bookmark.pub_date|date:"DATE_FORMAT" }}</span>
            </span>
            <span class="flex flex-row space-x-0.5">
              {% for tag in bookmark.tags.all %}
              <span class="text-[11px] bg-gray-200 text-gray-500 px-1 hover:bg-gray-500 hover:text-white">
                <a href="{% url 'bookmark:bookmark-list-by-tag' tag.slug %}">{{ tag.name }}</a>
              </span>
              {% endfor %}
            </span>
          </div>
          {% endif %}
        </div>
        {% else %}
        {% endif %}
      {% endif %}
    </div>
    {% include "bookmark/sidebar.html" %}
  </div>
</section>

{% endblock %}

bookmark/templates/bookmark/bookmark_list.html
{% extends "bookmark/base.html" %}{% load static %}{% load bookmark_extras %}
{% block titlepage %}Bookmarks - {{ block.super }}{% endblock %}
{% block content %}

<section class="container flex flex-col mx-auto px-8 lg:px-32 my-4">
  {% include "bookmark/content_tabs.html" %}
  <div class="border-y-4 border-t-blue-500 border-b-gray-300 pt-3 pb-2 mb-3">
    <div class="text-gray-700">
      {% if tag %}
      The latest bookmarks on Delicioso with the tag
      <a href="{% url 'bookmark:bookmark-list-by-tag' tag.slug %}" class="font-semibold hover:underline">{{ tag.name }}</a>
      <a href="{% url 'bookmark:bookmark-list-by-tag-feed' tag.slug %}" class="text-yellow-600">
        <i class="fa-solid fa-rss"></i>
      </a>
      {% else %}
      The most latest bookmarks on Delicioso right now
      {% endif %}
    </div>
    <div class="flex flex-col sm:flex-row space-y-2 sm:space-y-0 justify-between text-xs">
      {% if tag %}
      <p class="text-gray-500 font-semibold"><i class="fa-regular fa-bookmark"></i> {{ tag.content }}</p>
      {% else %}
      <p class="text-blue-600 font-semibold">
        <a href="{% url 'bookmark:bookmark-list' %}"><i class="fa-solid fa-bookmark"></i> See more latest bookmarks</a>
      </p>
      {% endif %}
      <p>
        <span class="text-gray-400">New bookmarks saved in the month</span>
        <span class="bg-blue-500 text-white p-1">{{ current_month_total_bookmarks }}</span>
      </p>
    </div>
  </div>
  {% include "bookmark/content_list.html" %}
</section>

{% endblock %}

bookmark/templates/bookmark/content_tabs.html
<ul class="flex flex-row space-x-1 text-white indent-3 text-sm">
  <li class="bg-blue-500 pr-3 font-semibold">
    <a href="{% url 'bookmark:bookmark-list' %}">Latest Bookmarks</a>
  </li>
  <li class="bg-gray-400 pr-3">Explore Tags</li>
  <li class="border border-dashed border-gray-200 text-gray-300 pr-3 hidden md:inline">
    <a href="javascript:(function(){var url=encodeURIComponent(window.location.href);var titleTag=document.querySelector('title');var title=titleTag&&titleTag.textContent?encodeURIComponent(titleTag.textContent):'';var descriptionTag=document.querySelector('meta[name=&quot;description&quot;]');var description=descriptionTag&&descriptionTag.getAttribute('content')?encodeURIComponent(descriptionTag.getAttribute('content')):'';var gahdUrl='https://gahd.net/admin/bookmark/bookmark/add/?site_url='+url+(title?'&title='+title:'')+(description?'&content='+description:'');window.open(gahdUrl,'gahdBookmark','location=1,links=0,scrollbars=1,toolbar=0,width=710,height=660');})();">
      Bookmark It!
    </a>
  </li>
</ul>

bookmark/templates/bookmark/search_result.html
{% extends "bookmark/base.html" %}{% load static %}
{% block titlepage %}Bookmarks - {{ block.super }}{% endblock %}
{% block content %}

<section class="container mx-auto px-8 lg:px-32 my-4 flex flex-col">
  {% include "bookmark/content_tabs.html" %}
  <div class="border-y-4 border-t-blue-500 border-b-gray-300 pt-3 pb-2 mb-3">
    <div class="text-gray-700">
      {% if search_result_list %}
      The following results were found for the term: <b>{{ search_term }}</b>
      {% else %}
      No results were found for the term: <b>{{ search_term }}</b>
      {% endif %}
    </div>
    <div class="flex flex-col sm:flex-row space-y-2 sm:space-y-0 justify-between text-xs">
      <p class="text-blue-600 font-semibold">
        <a href="{% url 'bookmark:bookmark-list' %}">
          <i class="fa-solid fa-bookmark"></i> See more latest bookmarks
        </a>
      </p>
      <p>
        <span class="text-gray-400">New bookmarks saved in the month</span>
        <span class="bg-blue-500 text-white p-1">{{ current_month_total_bookmarks }}</span>
      </p>
    </div>
  </div>
  {% include "bookmark/content_list.html" with bookmark_list=search_result_list %}
</section>

{% endblock %}

bookmark/templates/bookmark/sidebar.html
<aside class="hidden sm:flex sm:flex-col text-gray-500 sm:basis-1/6">
  <div class="bg-gray-200 px-4 font-semibold">Popular Tags</div>
  <ul class="px-4 divide-y text-sm">
    {% for ptag in popular_tags %}
    <li class="hover:text-blue-500 hover:font-medium">
      <a href="{% url 'bookmark:bookmark-list-by-tag' ptag.slug %}">
        {{ ptag }}
        <span class="text-xs text-gray-300">({{ ptag.bookmark_count }})</span>
      </a>
    </li>
    {% endfor %}
  </ul>
</aside>