api/urls.py
from rest_framework import routers

from api.views import SecretKeyViewSet

router = routers.DefaultRouter()

router.register('secrets', SecretKeyViewSet, 'secrets')

urlpatterns = router.urls

changelog/urls.py
from django.urls import path

from . import views

app_name = 'changelog'
urlpatterns = [
    path('', views.ChangelogListView.as_view(),
         name='changelog-list'),
    path('<slug:changelog_slug>/',
         views.ChangelogDetailView.as_view(), name='changelog-detail'),
]

changelog/models.py
from django.db import models

from core.models import Post
from core.utils.post import PostType


class Changelog(Post):
    pub_type = models.CharField(choices=PostType.POST_TYPES,
                                default=PostType.CHANGELOG, max_length=10)

    def __str__(self):
        return self.title

changelog/views.py
from django.db.models import Q
from django.shortcuts import redirect
from django.utils import timezone
from django.views import View
from django.views.generic import ListView

from changelog.models import Changelog
from core.utils.post import PostStatus


class ChangelogListView(ListView):
    """Changelog list"""

    def get_queryset(self):
        return (
            Changelog.objects.select_related("author")
            .prefetch_related("tags")
            .filter(
                Q(status=PostStatus.PUBLISHED), Q(pub_date__date__lte=timezone.now())
            )
        )


class ChangelogDetailView(View):
    def get(self, request, *args, **kwargs):
        detail = kwargs["changelog_slug"]
        return redirect(f"/changelog/#{detail}")

changelog/templates/changelog/changelog_list.html
{% extends "core/base.html" %}{% load static %}
{% block titlepage %}Changelog - {% endblock %}
{% block content %}
{% if changelog_list %}
<div class="flex mx-4 md:mx-auto my-8 max-w-md md:max-w-2xl justify-center">
  <h2 class="text-gray-800 font-bold">Changelog</h2>
</div>
<div class="flex mx-4 md:mx-auto my-8 max-w-md md:max-w-2xl">
  <div class="h-full top-0 z-0"></div>
  <ul class="list-none m-0 p-0">
    {% for changelog in changelog_list %}
    <li class="mb-2">
      <div class="flex items-center mb-1">
        {% if changelog.is_public %}
        <div class="bg-indigo-600 rounded-full h-4 w-4 border-gray-200 border-2 z-10"></div>
        {% elif not changelog.is_public and user == changelog.author %}
        <div class="bg-red-600 rounded-full h-4 w-4 border-gray-200 border-2 z-10"></div>
        {% else %}
        <div class="bg-teal-600 rounded-full h-4 w-4 border-gray-200 border-2 z-10"></div>
        {% endif %}
        <div class="flex-1 ml-4 font-medium flex items-center" id="{{ changelog.slug }}">
          {{ changelog.pub_date }} - {{ changelog.title }}
          <a href="{% url 'changelog:changelog-detail' changelog.slug %}">
            <svg class="h-4 w-4 ml-1 text-gray-200" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13.828 10.172a4 4 0 00-5.656 0l-4 4a4 4 0 105.656 5.656l1.102-1.101m-.758-4.899a4 4 0 005.656 0l4-4a4 4 0 00-5.656-5.656l-1.1 1.1" />
            </svg>
          </a>
        </div>
      </div>
      <div class="ml-12 text-justify post-content">
        {{ changelog.content_html|safe }}
      </div>
    </li>
    {% endfor %}
  </ul>
</div>
{% endif %}

{% if is_paginated %}
<div class="flex flex-col items-center my-12">
  <div class="flex text-gray-700">

    {% if page_obj.has_previous %}
    {% if page_obj.previous_page_number == 1 %}
    <a class="h-8 w-8 mr-1 flex justify-center items-center rounded-full bg-gray-200 cursor-pointer"
      href="{% url 'changelog:changelog-list' %}">
      <svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" fill="none" viewBox="0 0 24 24"
        stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
        class="feather feather-chevron-left w-4 h-4">
        <polyline points="15 18 9 12 15 6"></polyline>
      </svg>
    </a>
    {% else %}
    <a class="h-8 w-8 mr-1 flex justify-center items-center rounded-full bg-gray-200 cursor-pointer"
      href="{% url 'changelog:changelog-list' %}?page={{ page_obj.previous_page_number }}">
      <svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" fill="none" viewBox="0 0 24 24"
        stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
        class="feather feather-chevron-left w-4 h-4">
        <polyline points="15 18 9 12 15 6"></polyline>
      </svg>
    </a>
    {% endif %}
    {% else %}
    <div class="h-8 w-8 mr-1 flex justify-center items-center rounded-full bg-gray-200 cursor-not-allowed">
      <svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" fill="none" viewBox="0 0 24 24"
        stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
        class="feather feather-chevron-left w-4 h-4">
        <polyline points="15 18 9 12 15 6"></polyline>
      </svg>
    </div>
    {% endif %}

    <div class="flex h-8 font-medium rounded-full bg-gray-200">
      {% for i in paginator.page_range %}
      {% if page_obj.number == i %}
      {% if i == 1 %}
      <a class="w-8 md:flex justify-center items-center hidden cursor-pointer leading-5 transition duration-150 ease-in rounded-full bg-red-600 text-white"
        href="{% url 'changelog:changelog-list' %}">{{ i }}</a>
      <a class="w-8 h-8 md:hidden flex justify-center items-center cursor-pointer leading-5 transition duration-150 ease-in rounded-full bg-red-600 text-white"
        href="{% url 'changelog:changelog-list' %}">{{ i }}</a>
      {% else %}
      <a class="w-8 md:flex justify-center items-center hidden cursor-pointer leading-5 transition duration-150 ease-in rounded-full bg-red-600 text-white"
        href="{% url 'changelog:changelog-list' %}?page={{ i }}">{{ i }}</a>
      <a class="w-8 h-8 md:hidden flex justify-center items-center cursor-pointer leading-5 transition duration-150 ease-in rounded-full bg-red-600 text-white"
        href="{% url 'changelog:changelog-list' %}?page={{ i }}">{{ i }}</a>
      {% endif %}
      {% else %}
      {% if i == 1 %}
      <a class="w-8 md:flex justify-center items-center hidden cursor-pointer leading-5 transition duration-150 ease-in rounded-full"
        href="{% url 'changelog:changelog-list' %}">{{ i }}</a>
      {% else %}
      <a class="w-8 md:flex justify-center items-center hidden cursor-pointer leading-5 transition duration-150 ease-in rounded-full"
        href="{% url 'changelog:changelog-list' %}?page={{ i }}">{{ i }}</a>
      {% endif %}
      {% endif %}
      {% endfor %}
    </div>

    {% if page_obj.has_next %}
    <a class="h-8 w-8 ml-1 flex justify-center items-center rounded-full bg-gray-200 cursor-pointer"
      href="{% url 'changelog:changelog-list' %}?page={{ page_obj.next_page_number }}">
      <svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" fill="none" viewBox="0 0 24 24"
        stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
        class="feather feather-chevron-right w-4 h-4">
        <polyline points="9 18 15 12 9 6"></polyline>
      </svg>
    </a>
    {% else %}
    <div class="h-8 w-8 ml-1 flex justify-center items-center rounded-full bg-gray-200 cursor-not-allowed">
      <svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" fill="none" viewBox="0 0 24 24"
        stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
        class="feather feather-chevron-right w-4 h-4">
        <polyline points="9 18 15 12 9 6"></polyline>
      </svg>
    </div>
    {% endif %}

  </div>
</div>
{% endif %}

{% endblock %}