api/urls.py
from rest_framework import routers

from api.views import SecretKeyViewSet

router = routers.DefaultRouter()

router.register('secrets', SecretKeyViewSet, 'secrets')

urlpatterns = router.urls

bookmark/urls.py
from django.urls import path

from . import views
from bookmark import feeds

app_name = 'bookmark'
urlpatterns = [
    path('', views.BookmarkListView.as_view(), name='bookmark-list'),
    path('search/', views.SearchView.as_view(), name='search'),
    path('tags/<slug:tag_slug>/',
         views.BookmarkListByTagListView.as_view(),
         name='bookmark-list-by-tag'),
    path('tags/<slug:tag_slug>/feed/', feeds.BookmarksByTagFeed(),
         name='bookmark-list-by-tag-feed'),
    path('<slug:bookmark_slug>/', views.BookmarkDetailView.as_view(),
         name='bookmark-detail'),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.views.generic.base import RedirectView, TemplateView

from . import views, feeds

app_name = 'core'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),

    # REDIRECTS

    path('favicon.ico',
         RedirectView.as_view(url='static/img/favicon.ico', permanent=True),
         name='favicon'),
    path('index.xml', RedirectView.as_view(url='/feed/'), name='go-to-feed'),

    # OTHER SECTIONS WITH CUSTOM URLS

    path('humans.txt',
         TemplateView.as_view(template_name="core/humans.txt",
                              content_type='text/plain'),
         name='humans'),
    path('articles/', views.ArticleListView.as_view(), name='article-list'),
    path('feed/', feeds.LatestEntriesFeed(), name='feed'),
    path('feed/json/', views.JsonFeedView.as_view(), name='json-feed'),
    path('search/', views.SearchView.as_view(), name='search'),

    # TAGS

    path('tags/', views.TagListView.as_view(), name='tag-list'),
    # posts (articles, pages, and notes) by tag
    path('tags/<slug:tag_slug>/', views.PostsByTagListView.as_view(),
         name='post-list-by-tag'),
    # posts by tag feed
    path('tags/<slug:tag_slug>/feed/', feeds.EntriesByTagFeed(),
         name='post-list-by-tag-feed'),

    # PAGES AND ARTICLES

    # page detail or articles by category
    path('<slug:page_slug>/', views.PageOrCategoryView.as_view(),
         name='page-detail-or-article-list-by-category'),
    # articles by category feed
    path('<slug:category_slug>/feed/', feeds.EntriesByCategoryFeed(),
         name='article-list-by-category-feed'),
    # article detail
    path('<slug:category_slug>/<slug:article_slug>/',
         views.ArticleDetailView.as_view(), name='article-detail')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

note/urls.py
from django.urls import path

from . import views

app_name = 'note'
urlpatterns = [
    path('', views.NoteListView.as_view(), name='note-list'),
    path('<slug:note_slug>/', views.NoteDetailView.as_view(),
         name='note-detail'),
]

core/forms.py
from django import forms

from .models import Comment


class CommentForm(forms.ModelForm):
    """
    # post = forms.IntegerField()
     author = forms.CharField(label="Nombre *", max_length=60,
                              widget=forms.TextInput(
                                  attrs={'placeholder': 'Nombre'}))
     author_email = forms.EmailField(label="E-mail *", max_length=100,
                                     widget=forms.EmailInput(
                                         attrs={'placeholder': 'E-mail'}))
     author_url = forms.URLField(label="URL", max_length=200,
                                 widget=forms.URLInput(
                                     attrs={'placeholder': 'URL',
                                            'required': False}))
    # author_ip = forms.GenericIPAddressField(protocol='both', unpack_ipv4=True)
    # comment_date = forms.DateTimeField()
     title = forms.CharField(label="Título", max_length=200,
                             widget=forms.TextInput(
                                 attrs={'placeholder': 'Título',
                                        'required': False}))
     content = forms.CharField(label="Comentario *", widget=forms.Textarea(
                                     attrs={'placeholder': 'Comentario'}))
    # karma = forms.IntegerField()
    # approved = forms.BooleanField()
    # comment_parent = forms.IntegerField()
    # user = forms.IntegerField()
    """

    class Meta:
        model = Comment
        fields = ['author', 'author_email', 'author_url', 'title', 'content']
        labels = {
            'author': 'Nombre*',
            'author_email': 'E-mail*',
            'author_url': 'URL',
            'title': 'Título',
            'content': 'Comentario*'
        }

    """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        print('kwargs', kwargs)
        # if (self.request.user.username):
        #     pass
    """


class LoggedCommentForm(forms.ModelForm):
    """Form for authenticated user"""
    class Meta:
        model = Comment
        fields = ['title', 'content']
        labels = {
            'title': 'Título',
            'content': 'Comentario'
        }

core/views.py
from itertools import chain
from operator import attrgetter
import random

from django.db.models import Q
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.utils import timezone
from django.views import View
from django.views.generic import DetailView, ListView

from bookmark.models import Bookmark
from core.entry import Entry
from core.feeds import latest_entries_json_feed
from core.models import Article, Category, Page, Tag
from core.utils.post import RECENTLY, PostStatus
from note.models import Note


class IndexView(ListView):
    context_object_name = "latest_article_list"
    featured_image = ["escudo", "inti"]
    paginate_by = RECENTLY
    template_name = "core/index.html"

    def get_queryset(self):
        return Entry.get_post_list(True)[:RECENTLY]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["featured_image"] = self.get_featured_image()
        return context

    def get_featured_image(self):
        return f"img/{random.choice(self.featured_image)}.png"


class JsonFeedView(View):
    def get(self, request, *args, **kwargs):
        json_feed = latest_entries_json_feed()
        return JsonResponse(json_feed, content_type="application/feed+json")


class ArticleListView(ListView):
    """Article list"""

    paginate_by = RECENTLY

    def get_queryset(self):
        return Entry.get_published_article_list()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["categories"] = Category.objects.all()
        return context


class ArticlesByCategoryListView(ListView):
    """Article list by category"""

    paginate_by = RECENTLY

    def get_queryset(self):
        category = Category.objects.get(slug=self.kwargs["category_slug"])
        return Entry.get_published_article_list().filter(category=category.id)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["category"] = Category.objects.get(slug=self.kwargs["category_slug"])
        context["categories"] = Category.objects.all()
        context["latest_article_list"] = Entry.get_published_article_list()[:RECENTLY]
        return context


class ArticlesByTagListView(ListView):
    """Article list by tag"""

    paginate_by = RECENTLY

    def get_queryset(self):
        tag = Tag.objects.get(slug=self.kwargs["tag_slug"])
        return Entry.get_published_article_list().filter(tags=tag.id)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["tag"] = Tag.objects.get(slug=self.kwargs["tag_slug"])
        context["categories"] = Category.objects.all()
        context["latest_article_list"] = Entry.get_published_article_list()[:RECENTLY]
        return context


class PostsByTagListView(ListView):
    """Post (articles, pages, and notes) list by tag"""

    paginate_by = RECENTLY
    template_name = "core/post_list.html"
    context_object_name = "post_list"

    def get(self, *args, **kwargs):
        if not self.kwargs["tag_slug"].islower():
            return redirect("core:post-list-by-tag", self.kwargs["tag_slug"].lower())
        return super(PostsByTagListView, self).get(*args, **kwargs)

    def get_queryset(self):
        tag = get_object_or_404(Tag, slug=self.kwargs["tag_slug"])
        articles = Entry.get_published_article_list().filter(tags=tag.id)
        notes = Entry.get_published_note_list().filter(tags=tag.id)
        pages = Entry.get_published_page_list().filter(tags=tag.id)
        return sorted(
            chain(articles, notes, pages), key=attrgetter("pub_date"), reverse=True
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["tag"] = Tag.objects.get(slug=self.kwargs["tag_slug"])
        return context


class SearchView(View):
    def get(self, request, *args, **kwargs):
        q = request.GET.get("q") or None
        if q is None:
            return render(request, "core/search_result.html")
        # https://docs.djangoproject.com/en/3.0/topics/db/queries/#complex-lookups-with-q-objects
        article_search_result_list = (
            Article.objects.select_related("author")
            .prefetch_related("category")
            .prefetch_related("tags")
            .filter(
                Q(status=PostStatus.PUBLISHED),
                Q(pub_date__date__lte=timezone.now()),
                Q(title__icontains=q)
                | Q(content__icontains=q)
                | Q(tags__name__icontains=q),
            )
            .distinct()
        )
        bookmark_search_result_list = (
            Bookmark.objects.select_related("author")
            .prefetch_related("tags")
            .filter(
                Q(status=PostStatus.PUBLISHED),
                Q(pub_date__date__lte=timezone.now()),
                Q(title__icontains=q)
                | Q(content__icontains=q)
                | Q(tags__name__icontains=q),
            )
            .distinct()
        )
        note_search_result_list = (
            Note.objects.select_related("author")
            .prefetch_related("tags")
            .filter(
                Q(status=PostStatus.PUBLISHED),
                Q(pub_date__date__lte=timezone.now()),
                Q(title__icontains=q)
                | Q(content__icontains=q)
                | Q(tags__name__icontains=q),
            )
            .distinct()
        )
        page_search_result_list = (
            Page.objects.select_related("author")
            .prefetch_related("tags")
            .filter(
                Q(status=PostStatus.PUBLISHED),
                Q(pub_date__date__lte=timezone.now()),
                Q(title__icontains=q)
                | Q(content__icontains=q)
                | Q(tags__name__icontains=q),
            )
            .distinct()
        )
        search_result_list = sorted(
            chain(
                article_search_result_list,
                bookmark_search_result_list,
                note_search_result_list,
                page_search_result_list,
            ),
            key=attrgetter("pub_date"),
            reverse=True,
        )
        return render(
            request,
            "core/search_result.html",
            {"search_result_list": search_result_list, "search_term": q},
        )


class PageOrCategoryView(View):
    """Page or Articles by Category"""

    def get(self, request, *args, **kwargs):
        if not self.kwargs["page_slug"].islower():
            return redirect(
                "core:page-detail-or-article-list-by-category",
                self.kwargs["page_slug"].lower(),
            )

        page = (
            Page.objects.select_related("author")
            .select_related("parent")
            .prefetch_related("tags")
            .filter(slug=self.kwargs["page_slug"])
        )
        if page.count() != 0:
            return render(request, "core/page_detail.html", {"page": page.first()})
        category = get_object_or_404(Category, slug=self.kwargs["page_slug"])

        context = dict()
        context["post_list"] = Entry.get_published_article_list().filter(
            category=category.id
        )
        context["category"] = category
        context["categories"] = Category.objects.all()
        context["latest_article_list"] = Entry.get_published_article_list()[:RECENTLY]
        return render(request, "core/post_list.html", context)


class ArticleDetailView(DetailView):
    """Article detail"""

    model = Article
    slug_url_kwarg = "article_slug"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["latest_article_list"] = Entry.get_published_article_list()[:RECENTLY]
        context["categories"] = Category.objects.all()
        context["previous_article"] = (
            Entry.get_published_article_list()
            .select_related("author")
            .prefetch_related("tags")
            .filter(pub_date__lt=self.object.pub_date)
            .order_by("-pub_date")
            .first()
        )
        context["next_article"] = (
            Entry.get_published_article_list()
            .select_related("author")
            .prefetch_related("tags")
            .filter(pub_date__gt=self.object.pub_date)
            .order_by("pub_date")
            .first()
        )
        print(context)
        return context


class PageDetailView(DetailView):
    """Page detail"""

    model = Page
    slug_url_kwarg = "page_slug"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class TagListView(ListView):
    """Tag list"""

    model = Tag

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

core/templates/core/article_list.html
{% extends "core/base_blog.html" %}{% load static %}
{% block titlepage %}{% if category %}{{ category.name }} - {% elif tag %}{{ tag.name }} - {% else %}Articles - {% endif %}{% endblock %}
{% block feed %}{% if category %}
  <link rel="alternate" href="{% url 'core:article-list-by-category-feed' category.slug %}" type="application/atom+xml" title="Gustavo Huarcaya - {{ category.name }}">{% elif tag %}
  <link rel="alternate" href="{% url 'core:post-list-by-tag-feed' tag.slug %}" type="application/atom+xml" title="Gustavo Huarcaya - {{ tag.name }}">{% else %}
  <link rel="alternate" href="{% url 'core:feed' %}" type="application/atom+xml" title="Gustavo Huarcaya (Atom)">
  <link rel="alternate" href="{% url 'core:json-feed' %}" type="application/feed+json" title="Gustavo Huarcaya (JSON)" />{% endif %}{% endblock %}
  {% block meta %}<meta name="description" content="Gustavo Huarcaya{% if category %}, anotaciones de la categoría {{ category.name }}{% elif tag %}, anotaciones del tag {{ tag.name }}{% else %}'s Weblog{% endif %}">
  <meta name="keywords" content="gustavo huarcaya, gustavo, huarcaya, {% if category %}{{ category.name }}{% elif tag %}{{ tag.name }}{% endif %}">{% endblock %}
  {% block ogp %}<meta property="og:title" content="{% if category %}{{ category.name }} - {% elif tag %}{{ tag.name }} - {% endif %}Gustavo Huarcaya">
  <meta property="og:description" content="Gustavo Huarcaya{% if category %}, anotaciones de la categoría {{ category.name }}{% elif tag %}, anotaciones del tag {{ tag.name }}{% else %}'s Weblog{% endif %}">
  <meta property="og:type" content="website">
  <meta property="og:url" content="{{ request.scheme }}://{{ request.get_host }}{{ request.get_full_path }}">
  <meta property="og:site_name" content="gahd.net">
  <meta property="og:image" content="{{ request.scheme }}://{{ request.get_host }}{% static 'img/inti.png' %}">{% endblock %}
{% block content %}
{% if article_list %}
{% for article in article_list %}
{% if article.is_public %}
<article class="post-card">
  <div class="post-post">
    <section class="text-xs text-gray-800 flex items-center space-x-1">
      <i class="fa-regular fa-folder-open"></i>
      <a href="{% url 'core:page-detail-or-article-list-by-category' article.category.slug %}">{{ article.category }}</a>
    </section>
    <section class="post-header">
      <h2 class="text-lg font-semibold text-gray-900 -mt-1">
        <a href="{% url 'core:article-detail' article.category.slug article.slug %}">{{ article.title }}</a>
      </h2>
      <small class="text-sm text-gray-700"></small>
    </section>
    <section class="text-xs text-gray-700">
      {{ article.last_modified|date:'DATETIME_FORMAT' }}
    </section>
    <section class="post-content">
      {{ article.content_html|safe|truncatewords_html:"50" }}
    </section>
    <section class="flex mr-2 text-gray-700 text-sm mr-8">
      <a class="text-red-600 inline-flex items-center" href="{% url 'core:article-detail' article.category.slug article.slug %}">
        Read more
        <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
          class="w-4 h-4" viewBox="0 0 24 24">
          <path d="M5 12h14M12 5l7 7-7 7"></path>
        </svg>
      </a>
    </section>
    {% if article.tags.count %}
    <section class="post-footer">
      {% for tag in article.tags.all %}
      <div class="flex mr-2 text-xs text-blue-600 mr-3">
        <a href="{% url 'core:post-list-by-tag' tag.slug %}">#{{ tag.name }}</a>
      </div>
      {% endfor %}
      {% comment %}
      <div class="flex mr-2 text-gray-700 text-sm mr-8">
        <svg fill="none" viewBox="0 0 24 24" class="w-4 h-4 mr-1" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 8h2a2 2 0 012 2v6a2 2 0 01-2 2h-2v4l-4-4H9a1.994 1.994 0 01-1.414-.586m0 0L11 14h4a2 2 0 002-2V6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2v4l.586-.586z"/>
        </svg>
        <span>8</span>
      </div>
      <div class="flex mr-2 text-gray-700 text-sm mr-4">
        <svg fill="none" viewBox="0 0 24 24" class="w-4 h-4 mr-1" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-8l-4-4m0 0L8 8m4-4v12"/>
        </svg>
        <span>share</span>
      </div>
      {% endcomment %}
    </section>
    {% endif %}
  </div>
</article>
{% elif not article.is_public and user == article.author %}
<article class="post-private-card">
  <div class="post-post">
    <section class="text-xs text-gray-800 flex items-center">
      <svg class="text-grey w-3 h-3 mr-2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 18 18" fill="currentColor">
        <path fill-rule="evenodd" d="M2 6a2 2 0 012-2h4l2 2h4a2 2 0 012 2v1H8a3 3 0 00-3 3v1.5a1.5 1.5 0 01-3 0V6z" clip-rule="evenodd" />
        <path d="M6 12a2 2 0 012-2h8a2 2 0 012 2v2a2 2 0 01-2 2H2h2a2 2 0 002-2v-2z" />
      </svg>
      <a href="{% url 'core:page-detail-or-article-list-by-category' article.category.slug %}">{{ article.category }}</a>
    </section>
    <section class="post-header">
      <h2 class="text-lg font-semibold text-gray-900 -mt-1">
        <a href="{% url 'core:article-detail' article.category.slug article.slug %}">{{ article.title }}</a>
      </h2>
      <small class="text-sm text-gray-700"></small>
    </section>
    <section class="text-xs text-gray-700">
      {{ article.last_modified|date:'DATETIME_FORMAT' }}
    </section>
    <section class="post-content">
      {{ article.content_html|safe|truncatewords_html:"50" }}
    </section>
    <section class="flex mr-2 text-gray-700 text-sm mr-8 items-center">
      <a class="text-red-600 inline-flex items-center" href="{% url 'core:article-detail' article.category.slug article.slug %}">
        Read more...
      </a>
    </section>
    {% if article.tags.count %}
    <section class="post-footer">
      {% for tag in article.tags.all %}
      <div class="flex mr-2 text-xs text-blue-600 mr-3">
        <a href="{% url 'core:post-list-by-tag' tag.slug %}">#{{ tag.name }}</a>
      </div>
      {% endfor %}
      {% comment %}
      <div class="flex mr-2 text-gray-700 text-sm mr-8">
        <svg fill="none" viewBox="0 0 24 24" class="w-4 h-4 mr-1" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 8h2a2 2 0 012 2v6a2 2 0 01-2 2h-2v4l-4-4H9a1.994 1.994 0 01-1.414-.586m0 0L11 14h4a2 2 0 002-2V6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2v4l.586-.586z"/>
        </svg>
        <span>8</span>
      </div>
      <div class="flex mr-2 text-gray-700 text-sm mr-4">
        <svg fill="none" viewBox="0 0 24 24" class="w-4 h-4 mr-1" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-8l-4-4m0 0L8 8m4-4v12"/>
        </svg>
        <span>share</span>
      </div>
      {% endcomment %}
    </section>
    {% endif %}
  </div>
</article>
{% endif %}
{% endfor %}
{% else %}
<section class="flex my-10">
  <div class="w-1/5 m-auto rounded-md overflow-hidden">
    <img src="{% static 'img/cow.png' %}" alt="" class="w-full object-cover object-center py-4" />
    <div class="p-4">
      <p class="mb-1 text-gray-900 font-semibold">Moo!</p>
      <span class="text-gray-700">I've got nothing to show.</span>
    </div>
  </div>
</section>
{% endif %}

{% if is_paginated %}
<section class="flex flex-col items-center my-12">
    <div class="flex text-gray-700">

    {% if page_obj.has_previous %}
    {% if page_obj.previous_page_number == 1 %}
    <a class="h-8 w-8 mr-1 flex justify-center items-center rounded-full bg-gray-200 cursor-pointer" href="{% url 'core:article-list' %}">
      <svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-chevron-left w-4 h-4">
        <polyline points="15 18 9 12 15 6"></polyline>
      </svg>
    </a>
    {% else %}
    <a class="h-8 w-8 mr-1 flex justify-center items-center rounded-full bg-gray-200 cursor-pointer" href="{% url 'core:article-list' %}?page={{ page_obj.previous_page_number }}">
      <svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-chevron-left w-4 h-4">
        <polyline points="15 18 9 12 15 6"></polyline>
      </svg>
    </a>
    {% endif %}
    {% else %}
    <div class="h-8 w-8 mr-1 flex justify-center items-center rounded-full bg-gray-200 cursor-not-allowed">
      <svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-chevron-left w-4 h-4">
        <polyline points="15 18 9 12 15 6"></polyline>
      </svg>
    </div>
    {% endif %}

  <div class="flex h-8 font-medium rounded-full bg-gray-200">
    {% for i in paginator.page_range %}
    {% if page_obj.number == i %}
    {% if i == 1 %}
    <a class="w-8 md:flex justify-center items-center hidden cursor-pointer leading-5 transition duration-150 ease-in rounded-full bg-red-600 text-white" href="{% url 'core:article-list' %}">{{ i }}</a>
    <a class="w-8 h-8 md:hidden flex justify-center items-center cursor-pointer leading-5 transition duration-150 ease-in rounded-full bg-red-600 text-white" href="{% url 'core:article-list' %}">{{ i }}</a>
    {% else %}
    <a class="w-8 md:flex justify-center items-center hidden cursor-pointer leading-5 transition duration-150 ease-in rounded-full bg-red-600 text-white" href="{% url 'core:article-list' %}?page={{ i }}">{{ i }}</a>
    <a class="w-8 h-8 md:hidden flex justify-center items-center cursor-pointer leading-5 transition duration-150 ease-in rounded-full bg-red-600 text-white" href="{% url 'core:article-list' %}?page={{ i }}">{{ i }}</a>
    {% endif %}
    {% else %}
    {% if i == 1 %}
    <a class="w-8 md:flex justify-center items-center hidden cursor-pointer leading-5 transition duration-150 ease-in rounded-full" href="{% url 'core:article-list' %}">{{ i }}</a>
    {% else %}
    <a class="w-8 md:flex justify-center items-center hidden cursor-pointer leading-5 transition duration-150 ease-in rounded-full" href="{% url 'core:article-list' %}?page={{ i }}">{{ i }}</a>
    {% endif %}
    {% endif %}
    {% endfor %}
  </div>

    {% if page_obj.has_next %}
    <a class="h-8 w-8 ml-1 flex justify-center items-center rounded-full bg-gray-200 cursor-pointer" href="{% url 'core:article-list' %}?page={{ page_obj.next_page_number }}">
      <svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-chevron-right w-4 h-4">
        <polyline points="9 18 15 12 9 6"></polyline>
      </svg>
    </a>
    {% else %}
    <div class="h-8 w-8 ml-1 flex justify-center items-center rounded-full bg-gray-200 cursor-not-allowed">
      <svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-chevron-right w-4 h-4">
        <polyline points="9 18 15 12 9 6"></polyline>
      </svg>
    </div>
    {% endif %}

    </div>
</section>
{% endif %}
{% endblock %}

core/templates/core/base_article.html
{% extends "core/base.html" %}

core/templates/core/base_blog.html
{% extends "core/base.html" %}

core/templates/core/base_page.html
{% extends "core/base.html" %}

core/templates/core/tag_list.html
{% extends "core/base.html" %}
{% block titlepage %}Tags - {% endblock %}
{% block meta %}{% endblock %}
{% block article %}
<article>
{% if tag_list %}
  <header>
    <h2 class="ui header"><i class="tags icon"></i> Tags</h2>
  </header>
  <section class="ui container">
    {% for tag in tag_list %}
    <a class="ui tag label" href="{% url 'core:post-list-by-tag' tag.slug %}">{{ tag.name }}</a>
    {% endfor %}
  </section>
{% else %}
  <div class="ui info icon message">
    <i class="tags icon"></i>
    <div class="content">
      <div class="header">
        0 tags
      </div>
      <p>No se encontraron tags registrados.</p>
    </div>
  </div>
{% endif %}
</article>
{% endblock %}