api/urls.py
from rest_framework import routers

from api.views import SecretKeyViewSet

router = routers.DefaultRouter()

router.register('secrets', SecretKeyViewSet, 'secrets')

urlpatterns = router.urls

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.views.generic.base import RedirectView, TemplateView

from . import views, feeds

app_name = 'core'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),

    # REDIRECTS

    path('favicon.ico',
         RedirectView.as_view(url='static/img/favicon.ico', permanent=True),
         name='favicon'),
    path('index.xml', RedirectView.as_view(url='/feed/'), name='go-to-feed'),

    # OTHER SECTIONS WITH CUSTOM URLS

    path('humans.txt',
         TemplateView.as_view(template_name="core/humans.txt",
                              content_type='text/plain'),
         name='humans'),
    path('articles/', views.ArticleListView.as_view(), name='article-list'),
    path('feed/', feeds.LatestEntriesFeed(), name='feed'),
    path('feed/json/', views.JsonFeedView.as_view(), name='json-feed'),
    path('search/', views.SearchView.as_view(), name='search'),

    # TAGS

    path('tags/', views.TagListView.as_view(), name='tag-list'),
    # posts (articles, pages, and notes) by tag
    path('tags/<slug:tag_slug>/', views.PostsByTagListView.as_view(),
         name='post-list-by-tag'),
    # posts by tag feed
    path('tags/<slug:tag_slug>/feed/', feeds.EntriesByTagFeed(),
         name='post-list-by-tag-feed'),

    # PAGES AND ARTICLES

    # page detail or articles by category
    path('<slug:page_slug>/', views.PageOrCategoryView.as_view(),
         name='page-detail-or-article-list-by-category'),
    # articles by category feed
    path('<slug:category_slug>/feed/', feeds.EntriesByCategoryFeed(),
         name='article-list-by-category-feed'),
    # article detail
    path('<slug:category_slug>/<slug:article_slug>/',
         views.ArticleDetailView.as_view(), name='article-detail')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

note/urls.py
from django.urls import path

from . import views

app_name = 'note'
urlpatterns = [
    path('', views.NoteListView.as_view(), name='note-list'),
    path('<slug:note_slug>/', views.NoteDetailView.as_view(),
         name='note-detail'),
]

note/models.py
from django.db import models
from django.urls import reverse

from core.models import Post
from core.utils.post import PostType


class Note(Post):
    pub_type = models.CharField(choices=PostType.POST_TYPES,
                                default=PostType.NOTE, max_length=10)

    def get_absolute_url(self):
        return reverse('note:note-detail', kwargs={'note_slug': self.slug})

    def __str__(self):
        return self.title

note/views.py
from django.views.generic import DetailView, ListView

from core.entry import Entry
from core.utils.post import RECENTLY
from note.models import Note


class NoteListView(ListView):
    """Note list"""

    model = Note
    paginate_by = RECENTLY

    def get_queryset(self):
        return Entry.get_published_note_list()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class NoteDetailView(DetailView):
    """Note detail"""

    model = Note
    slug_url_kwarg = "note_slug"

note/templates/note/note_detail.html
{% extends "note/base.html" %}{% load static %}
{% block titlepage %}{% if note %}{{ note.title }} - {% endif %}{% endblock %}
{% block content %}

{% if note %}
{% if note.is_public %}
<article class="note-card">
  <div class="note-post">
    <section class="note-header">
      <img class="w-12 h-12 rounded-full object-cover mr-4" src="{% static 'img/inti.png' %}" alt="avatar">
      <div>
        <h2 class="text-lg font-semibold text-gray-900 -mt-1"><a href="{% url 'note:note-detail' note.slug %}">{{ note.title }}</a></h2>
        <small class="text-sm text-gray-700"></small>
        <p class="text-xs text-gray-700">{{ note.last_modified|date:'DATETIME_FORMAT' }}</p>
      </div>
    </section>
    <section class="note-content">
      {{ note.content_html|safe }}
    </section>
    {% if note.tags.count %}
    <section class="note-footer">
      {% for tag in note.tags.all %}
      <div class="flex mr-2 text-xs text-blue-600 mr-3">
        <a href="{% url 'core:post-list-by-tag' tag.slug %}">#{{ tag.name }}</a>
      </div>
      {% endfor %}
      {% comment %}
      <div class="flex mr-2 text-gray-700 text-sm mr-8">
        <svg fill="none" viewBox="0 0 24 24" class="w-4 h-4 mr-1" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 8h2a2 2 0 012 2v6a2 2 0 01-2 2h-2v4l-4-4H9a1.994 1.994 0 01-1.414-.586m0 0L11 14h4a2 2 0 002-2V6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2v4l.586-.586z"/>
        </svg>
        <span>8</span>
      </div>
      <div class="flex mr-2 text-gray-700 text-sm mr-4">
        <svg fill="none" viewBox="0 0 24 24" class="w-4 h-4 mr-1" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-8l-4-4m0 0L8 8m4-4v12"/>
        </svg>
        <span>share</span>
      </div>
      {% endcomment %}
    </section>
    {% endif %}
  </div>
</article>
{% elif not note.is_public and user == note.author %}
<article class="note-private-card">
  <div class="note-post">
    <section class="note-header">
      <img class="w-12 h-12 rounded-full object-cover mr-4" src="{% static 'img/inti.png' %}" alt="avatar">
      <div>
        <h2 class="text-lg font-semibold text-gray-900 -mt-1"><a href="{% url 'note:note-detail' note.slug %}">{{ note.title }}</a></h2>
      <small class="text-sm text-gray-700"></small>
      <p class="text-xs text-gray-700">{{ note.last_modified|date:'DATETIME_FORMAT' }}</p>
      </div>
    </section>
    <section class="note-content">
      {{ note.content_html|safe }}
    </section>
    {% if note.tags.count %}
    <section class="note-footer">
      {% for tag in note.tags.all %}
      <div class="flex mr-2 text-xs text-blue-600 mr-3">
        <a href="{% url 'core:post-list-by-tag' tag.slug %}">#{{ tag.name }}</a>
      </div>
      {% endfor %}
      {% comment %}
      <div class="flex mr-2 text-gray-700 text-sm mr-8">
        <svg fill="none" viewBox="0 0 24 24" class="w-4 h-4 mr-1" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 8h2a2 2 0 012 2v6a2 2 0 01-2 2h-2v4l-4-4H9a1.994 1.994 0 01-1.414-.586m0 0L11 14h4a2 2 0 002-2V6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2v4l.586-.586z"/>
        </svg>
        <span>8</span>
      </div>
      <div class="flex mr-2 text-gray-700 text-sm mr-4">
        <svg fill="none" viewBox="0 0 24 24" class="w-4 h-4 mr-1" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-8l-4-4m0 0L8 8m4-4v12"/>
        </svg>
        <span>share</span>
      </div>
      {% endcomment %}
    </section>
    {% endif %}
  </div>
</article>
{% endif %}

{% else %}
{% endif %}

{% endblock %}

note/templates/note/note_list.html
{% extends "note/base.html" %}{% load static %}
{% block titlepage %}Notes - {% endblock %}
{% block content %}

{% if note_list %}
{% for note in note_list %}
{% if note.is_public %}
<article class="note-card">
  <div class="note-post">
    <section class="note-header">
      <img class="w-12 h-12 rounded-full object-cover mr-4" src="{% static 'img/inti.png' %}" alt="avatar">
      <div>
        <h2 class="text-lg font-semibold text-gray-900 -mt-1">
          <a href="{% url 'note:note-detail' note.slug %}">{{ note.title }}</a>
        </h2>
        <small class="text-sm text-gray-700"></small>
        <p class="text-xs text-gray-700">{{ note.last_modified|date:'DATETIME_FORMAT' }}</p>
      </div>
    </section>
    <section class="note-content">
      {{ note.content_html|safe|truncatewords_html:"25" }}
    </section>
    {% if note.tags.count %}
    <section class="note-footer">
      {% for tag in note.tags.all %}
      <div class="flex mr-2 text-xs text-blue-600 mr-3">
        <a href="{% url 'core:post-list-by-tag' tag.slug %}">#{{ tag.name }}</a>
      </div>
      {% endfor %}
      {% comment %}
      <div class="flex mr-2 text-gray-700 text-sm mr-8">
        <svg fill="none" viewBox="0 0 24 24" class="w-4 h-4 mr-1" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 8h2a2 2 0 012 2v6a2 2 0 01-2 2h-2v4l-4-4H9a1.994 1.994 0 01-1.414-.586m0 0L11 14h4a2 2 0 002-2V6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2v4l.586-.586z"/>
        </svg>
        <span>8</span>
      </div>
      <div class="flex mr-2 text-gray-700 text-sm mr-4">
        <svg fill="none" viewBox="0 0 24 24" class="w-4 h-4 mr-1" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-8l-4-4m0 0L8 8m4-4v12"/>
        </svg>
        <span>share</span>
      </div>
      {% endcomment %}
    </section>
    {% endif %}
  </div>
</article>
{% elif not note.is_public and user == note.author %}
<article class="note-private-card">
  <div class="note-post">
    <section class="note-header">
      <img class="w-12 h-12 rounded-full object-cover mr-4" src="{% static 'img/inti.png' %}" alt="avatar">
      <div>
        <h2 class="text-lg font-semibold text-gray-900 -mt-1">
          <a href="{% url 'note:note-detail' note.slug %}">{{ note.title }}</a>
        </h2>
        <small class="text-sm text-gray-700"></small>
        <p class="text-xs text-gray-700">{{ note.last_modified|date:'DATETIME_FORMAT' }}</p>
      </div>
    </section>
    <section class="note-content">
      {{ note.content_html|safe|truncatewords_html:"25" }}
    </section>
    {% if note.tags.count %}
    <section class="note-footer">
      {% for tag in note.tags.all %}
      <div class="flex mr-2 text-xs text-blue-600 mr-3">
        <a href="{% url 'core:post-list-by-tag' tag.slug %}">#{{ tag.name }}</a>
      </div>
      {% endfor %}
      {% comment %}
      <div class="flex mr-2 text-gray-700 text-sm mr-8">
        <svg fill="none" viewBox="0 0 24 24" class="w-4 h-4 mr-1" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 8h2a2 2 0 012 2v6a2 2 0 01-2 2h-2v4l-4-4H9a1.994 1.994 0 01-1.414-.586m0 0L11 14h4a2 2 0 002-2V6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2v4l.586-.586z"/>
        </svg>
        <span>8</span>
      </div>
      <div class="flex mr-2 text-gray-700 text-sm mr-4">
        <svg fill="none" viewBox="0 0 24 24" class="w-4 h-4 mr-1" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-8l-4-4m0 0L8 8m4-4v12"/>
        </svg>
        <span>share</span>
      </div>
      {% endcomment %}
    </section>
    {% endif %}
  </div>
</article>
{% endif %}
{% endfor %}
{% else %}
{% endif %}

{% if is_paginated %}
<section class="flex flex-col items-center my-12">
  <div class="flex text-gray-700">

    {% if page_obj.has_previous %}
      {% if page_obj.previous_page_number == 1 %}
      <a class="h-8 w-8 mr-1 flex justify-center items-center rounded-full bg-gray-200 cursor-pointer" href="{% url 'note:note-list' %}">
        <svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-chevron-left w-4 h-4">
          <polyline points="15 18 9 12 15 6"></polyline>
        </svg>
      </a>
      {% else %}
      <a class="h-8 w-8 mr-1 flex justify-center items-center rounded-full bg-gray-200 cursor-pointer" href="{% url 'note:note-list' %}?page={{ page_obj.previous_page_number }}">
        <svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-chevron-left w-4 h-4">
          <polyline points="15 18 9 12 15 6"></polyline>
        </svg>
      </a>
      {% endif %}
    {% else %}
      <div class="h-8 w-8 mr-1 flex justify-center items-center rounded-full bg-gray-200 cursor-not-allowed">
        <svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-chevron-left w-4 h-4">
          <polyline points="15 18 9 12 15 6"></polyline>
        </svg>
      </div>
    {% endif %}

    <div class="flex h-8 font-medium rounded-full bg-gray-200">
    {% for i in paginator.get_elided_page_range %}
    {% if page_obj.number == i %}
      {% if i == 1 %}
      <a class="w-8 md:flex justify-center items-center hidden cursor-pointer leading-5 transition duration-150 ease-in rounded-full bg-red-600 text-white" href="{% url 'note:note-list' %}">{{ i }}</a>
      <a class="w-8 h-8 md:hidden flex justify-center items-center cursor-pointer leading-5 transition duration-150 ease-in rounded-full bg-red-600 text-white" href="{% url 'note:note-list' %}">{{ i }}</a>
      {% else %}
      <a class="w-8 md:flex justify-center items-center hidden cursor-pointer leading-5 transition duration-150 ease-in rounded-full bg-red-600 text-white" href="{% url 'note:note-list' %}?page={{ i }}">{{ i }}</a>
      <a class="w-8 h-8 md:hidden flex justify-center items-center cursor-pointer leading-5 transition duration-150 ease-in rounded-full bg-red-600 text-white" href="{% url 'note:note-list' %}?page={{ i }}">{{ i }}</a>
      {% endif %}
    {% else %}
      {% if i == 1 %}
      <a class="w-8 md:flex justify-center items-center hidden cursor-pointer leading-5 transition duration-150 ease-in rounded-full" href="{% url 'note:note-list' %}">{{ i }}</a>
      {% elif i == paginator.ELLIPSIS %}

        {% if page_obj.number not in paginator.get_elided_page_range %}
          {% if page_obj.previous_page_number not in paginator.get_elided_page_range %}
            <a class="w-8 md:flex justify-center items-center hidden cursor-pointer leading-5 transition duration-150 ease-in rounded-full">{{ i }}</a>
            <a class="w-8 md:flex justify-center items-center hidden cursor-pointer leading-5 transition duration-150 ease-in rounded-full">{{ page_obj.previous_page_number }}</a>
          {% endif %}
          <a class="w-8 md:flex justify-center items-center hidden cursor-pointer leading-5 transition duration-150 ease-in rounded-full bg-red-600 text-white">{{ page_obj.number }}</a>
          {% if page_obj.next_page_number not in paginator.get_elided_page_range %}
            <a class="w-8 md:flex justify-center items-center hidden cursor-pointer leading-5 transition duration-150 ease-in rounded-full">{{ page_obj.next_page_number }}</a>
            <a class="w-8 md:flex justify-center items-center hidden cursor-pointer leading-5 transition duration-150 ease-in rounded-full">{{ i }}</a>
          {% endif %}
        {% else %}
          <a class="w-8 md:flex justify-center items-center hidden cursor-pointer leading-5 transition duration-150 ease-in rounded-full">{{ i }}</a>
        {% endif %}

      {% else %}
      <a class="w-8 md:flex justify-center items-center hidden cursor-pointer leading-5 transition duration-150 ease-in rounded-full" href="{% url 'note:note-list' %}?page={{ i }}">{{ i }}</a>
      {% endif %}
    {% endif %}
    {% endfor %}
    </div>

    {% if page_obj.has_next %}
    <a class="h-8 w-8 ml-1 flex justify-center items-center rounded-full bg-gray-200 cursor-pointer" href="{% url 'note:note-list' %}?page={{ page_obj.next_page_number }}">
      <svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-chevron-right w-4 h-4">
        <polyline points="9 18 15 12 9 6"></polyline>
      </svg>
    </a>
    {% else %}
    <div class="h-8 w-8 ml-1 flex justify-center items-center rounded-full bg-gray-200 cursor-not-allowed">
      <svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-chevron-right w-4 h-4">
        <polyline points="9 18 15 12 9 6"></polyline>
      </svg>
    </div>
    {% endif %}
  </div>
</section>
{% endif %}

{% endblock %}